CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    index INT,
    description TEXT,
    task_status_id BIGINT,
    assignee_id BIGINT,
    created_at DATE,
    FOREIGN KEY (task_status_id) REFERENCES task_status(id),
    FOREIGN KEY (assignee_id) REFERENCES users(id)
);

CREATE TABLE task_labels (
    task_id BIGINT NOT NULL,
    label_id BIGINT NOT NULL,
    PRIMARY KEY (task_id, label_id),
    FOREIGN KEY (task_id) REFERENCES tasks(id),
    FOREIGN KEY (label_id) REFERENCES labels(id)
);