name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build and test with Gradle (with coverage)
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.9
          arguments: jacocoTestReport
      - name: Upload coverage to QltY
        uses: qltysh/qlty-action/coverage@v1
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: build/reports/jacoco/test/jacocoTestReport.xml